Repository Treepat/Treepat, pull requests merged in 2020-04, with the labels that each got.

#82 Added JDK prerequisite
  README.md
Labels: documentation

#81 Create unit tests for operators.
  src/test/kotlin/MockValues.kt
  src/test/kotlin/operators/BreadthClosureFunctionKtTest.kt
  src/test/kotlin/operators/ChildFunctionKtTest.kt
  src/test/kotlin/operators/DepthClosureFunctionKtTest.kt
  src/test/kotlin/operators/DepthTermFunctionKtTest.kt
  src/test/kotlin/operators/DotFunctionKtTest.kt
  src/test/kotlin/operators/NodeFunctionKtTest.kt
  src/test/kotlin/operators/SiblingFunctionKtTest.kt
  src/test/kotlin/operators/TreepatFunctionKtTest.kt
  src/test/kotlin/operators/UnionFunctionKtTest.kt
  src/test/kotlin/operators/VisitorFunctionKtTest.kt
Labels: enhancement

#91 Updated README
  README.md
Labels: documentation

#92 Release 1.1.2
  README.md
Labels: documentation

#95 Github maven deploy in Github Packages
  .github/workflows/maven.yml
  .github/workflows/release.yml
  pom.xml
  settings.xml
Labels: enhancement

#96 Github maven deploy in Github Packages (#95)
  .github/workflows/maven.yml
  .github/workflows/release.yml
  pom.xml
  settings.xml
Labels: enhancement

#101 Fix github actions Treppat CD
  .github/workflows/release.yml
Labels: bug

#102 Release 1.2.0
  .github/workflows/release.yml
Labels: enhancement
