Repository Treepat/Treepat, pull requests merged in 2020-03, with the labels that each got.

#14 Create module to create high-level function from an ASTNode
  src/main/java/Main.kt
  src/main/java/antlr/TreepatVisitorImplementationFunctions.kt
  src/main/java/functions/VisitorFunction.kt
Labels: enhancement

#15 Created unit tests for all visitor functions
  .github/workflows/maven.yml
  pom.xml
  src/test/java/functions/ChildFunctionKtTest.kt
  src/test/java/functions/MockValues.kt
  src/test/java/functions/NodeFunctionKtTest.kt
  src/test/java/functions/SiblingFunctionKtTest.kt
Labels: enhancement

#19 Refactor and clean code.
  src/main/java/Main.kt
  src/main/java/antlr/Treepat.g4
  src/main/java/antlr/TreepatVisitorImplementation.kt
  src/main/java/antlr/TreepatVisitorImplementationFunctions.kt
  src/main/java/antlr/generate/Treepat.interp
  src/main/java/antlr/generate/Treepat.tokens
  src/main/java/antlr/generate/TreepatBaseListener.java
  src/main/java/antlr/generate/TreepatBaseVisitor.java
  src/main/java/antlr/generate/TreepatLexer.interp
  src/main/java/antlr/generate/TreepatLexer.java
  src/main/java/antlr/generate/TreepatLexer.tokens
  src/main/java/antlr/generate/TreepatListener.java
  src/main/java/antlr/generate/TreepatParser.java
  src/main/java/antlr/generate/TreepatVisitor.java
  src/main/java/ast/ASTNode.kt
  src/main/java/ast/ASTNodes.kt
  src/main/java/ast/Child.kt
  src/main/java/ast/Node.kt
  src/main/java/ast/Sibling.kt
  src/main/java/functions/ChildFunction.kt
  src/main/java/functions/NodeFunction.kt
  src/main/java/functions/SiblingFunction.kt
  src/main/java/tree/ImpTargetTreeNode.kt
  src/main/java/tree/TargetTreeNode.kt
  src/test/java/functions/ChildFunctionKtTest.kt
  src/test/java/functions/NodeFunctionKtTest.kt
  src/test/java/functions/SiblingFunctionKtTest.kt
Labels: enhancement

#21 Fix bug in fibling function
  src/main/java/functions/SiblingFunction.kt
  src/test/java/functions/SiblingFunctionKtTest.kt
Labels: bug

#37 First release fixes and project license
  .idea/codeStyles/Project.xml
  LICENSE
  src/main/java/tree/ImpTargetTreeNode.kt
Labels: enhancement

#35 First release
  .github/pull_request_template.md
  .github/workflows/maven.yml
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/compiler.xml
  .idea/vcs.xml
  LICENSE
  pom.xml
  src/main/java/Main.kt
  src/main/java/antlr/TreepatVisitorImplementation.kt
  src/main/java/antlr/generate/Treepat.interp
  src/main/java/antlr/generate/Treepat.tokens
  src/main/java/antlr/generate/TreepatBaseListener.java
  src/main/java/antlr/generate/TreepatBaseVisitor.java
  src/main/java/antlr/generate/TreepatLexer.interp
  src/main/java/antlr/generate/TreepatLexer.java
  src/main/java/antlr/generate/TreepatLexer.tokens
  src/main/java/antlr/generate/TreepatListener.java
  src/main/java/antlr/generate/TreepatParser.java
  src/main/java/antlr/generate/TreepatVisitor.java
  src/main/java/antlr/tree_format/TreeFormat.g4
  src/main/java/antlr/tree_format/TreeFormatVisitorImplementation.kt
  src/main/java/antlr/treepat/Treepat.g4
  src/main/java/antlr/treepat/TreepatVisitorImplementation.kt
  src/main/java/ast/ASTNode.kt
  src/main/java/ast/ASTNodes.kt
  src/main/java/ast/Child.kt
  src/main/java/ast/Node.kt
  src/main/java/ast/Sibling.kt
  src/main/java/functions/ChildFunction.kt
  src/main/java/functions/NodeFunction.kt
  src/main/java/functions/SiblingFunction.kt
  src/main/java/functions/VisitorFunction.kt
  src/main/java/tree/ImpTargetTreeNode.kt
  src/main/java/tree/ImpTargetTreeNodeComparator.kt
  src/main/java/tree/TargetTreeNode.kt
  src/test/java/ast/ASTNodesKtTest.kt
  src/test/java/ast/child/1.in
  src/test/java/ast/child/1.msg
  src/test/java/ast/child/2.in
  src/test/java/ast/child/2.msg
  src/test/java/ast/child/2.out
  src/test/java/ast/mix/1.in
  src/test/java/ast/mix/1.msg
  src/test/java/ast/mix/2.in
  src/test/java/ast/mix/2.msg
  src/test/java/ast/node/1.in
  src/test/java/ast/node/1.msg
  src/test/java/ast/sibling/1.in
  src/test/java/ast/sibling/1.msg
  src/test/java/ast/sibling/2.in
  src/test/java/ast/sibling/2.msg
  src/test/java/ast/sibling/2.out
  src/test/java/functions/ChildFunctionKtTest.kt
  src/test/java/functions/MockValues.kt
  src/test/java/functions/NodeFunctionKtTest.kt
  src/test/java/functions/SiblingFunctionKtTest.kt
  test.tef
  test.tp
Labels: bug, enhancement

#49 Created union oerator and tests
  src/main/java/antlr/treepat/TreepatVisitorImplementation.kt
  src/main/java/ast/ASTNodes.kt
  src/main/java/functions/UnionFunction.kt
  src/main/java/functions/VisitorFunction.kt
  src/test/java/ast/ASTNodesKtTest.kt
  src/test/java/ast/union/1.in
  src/test/java/ast/union/1.msg
  src/test/java/ast/union/2.in
  src/test/java/ast/union/2.msg
  src/test/java/functions/UnionFunctionKtTest.kt
Labels: enhancement

#41 Correct Antlr grammar with some operators.
  src/main/java/Main.kt
  src/main/java/antlr/treepat/Treepat.g4
  src/main/java/antlr/treepat/TreepatVisitorImplementation.kt
  src/main/java/ast/ASTNodes.kt
  src/test/java/ast/ASTNodesKtTest.kt
  src/test/java/ast/child/3.in
  src/test/java/ast/child/3.msg
  src/test/java/ast/mix/2.msg
  src/test/java/ast/mix/3.in
  src/test/java/ast/mix/3.msg
  src/test/java/ast/node/2.in
  src/test/java/ast/node/2.msg
  src/test/java/ast/node/3.in
  src/test/java/ast/node/3.msg
  src/test/java/ast/sibling/3.in
  src/test/java/ast/sibling/3.msg
  src/test/java/ast/sibling/4.in
  src/test/java/ast/sibling/4.msg
  src/test/java/ast/sibling/4.out
  src/test/java/ast/sibling/5.in
  src/test/java/ast/sibling/5.msg
  src/test/java/ast/sibling/5.out
  src/test/java/ast/union/1.in
  src/test/java/ast/union/2.in
Labels: bug, enhancement

#56 Fix high level functions.
  src/main/java/antlr/treepat/TreepatVisitorImplementation.kt
  src/main/java/ast/ASTNodes.kt
  src/main/java/functions/BreadthClosureFunction.kt
  src/main/java/functions/CheckFunction.kt
  src/main/java/functions/ChildFunction.kt
  src/main/java/functions/NodeFunction.kt
  src/main/java/functions/SiblingFunction.kt
  src/main/java/functions/UnionFunction.kt
  src/main/java/functions/VisitorFunction.kt
  src/test/java/functions/BreadthClosureFunctionKtTest.kt
  src/test/java/functions/CheckFunctionKtTest.kt
  src/test/java/functions/ChildFunctionKtTest.kt
  src/test/java/functions/MockValues.kt
  src/test/java/functions/NodeFunctionKtTest.kt
  src/test/java/functions/SiblingFunctionKtTest.kt
  src/test/java/functions/UnionFunctionKtTest.kt
Labels: bug, enhancement

#50 Improve the way the matched nodes are displayed
  src/main/java/Main.kt
  src/main/java/tree/ImpTargetTreeNode.kt
  src/main/java/tree/TargetTreeNode.kt
  test.tef
  test.tp
Labels: enhancement

#59 Add dot operator
  src/main/java/antlr/treepat/Treepat.g4
  src/main/java/antlr/treepat/TreepatVisitorImplementation.kt
  src/main/java/ast/ASTNodes.kt
  src/main/java/functions/DotFunction.kt
  src/main/java/functions/VisitorFunction.kt
  src/test/java/ast/ASTNodesKtTest.kt
  src/test/java/ast/dot/1.in
  src/test/java/ast/dot/1.msg
  src/test/java/ast/dot/2.in
  src/test/java/ast/dot/2.msg
  src/test/java/ast/dot/3.in
  src/test/java/ast/dot/3.msg
  src/test/java/e2e/E2EKtTest.kt
  src/test/java/e2e/dot/1.msg
  src/test/java/e2e/dot/1.out
  src/test/java/e2e/dot/1.tef
  src/test/java/e2e/dot/1.tp
  src/test/java/e2e/dot/2.msg
  src/test/java/e2e/dot/2.out
  src/test/java/e2e/dot/2.tef
  src/test/java/e2e/dot/2.tp
  src/test/java/e2e/dot/3.msg
  src/test/java/e2e/dot/3.out
  src/test/java/e2e/dot/3.tef
  src/test/java/e2e/dot/3.tp
  src/test/java/e2e/mix/4.msg
  src/test/java/e2e/mix/4.out
  src/test/java/e2e/mix/4.tef
  src/test/java/e2e/mix/4.tp
Labels: enhancement

#60 Added support for multiple solutions in depth
  src/main/java/Main.kt
  src/main/java/antlr/treepat/Treepat.g4
  src/main/java/antlr/treepat/TreepatVisitorImplementation.kt
  src/main/java/ast/ASTNodes.kt
  src/main/java/functions/TreepatFunction.kt
  src/main/java/functions/VisitorFunction.kt
  src/main/java/tree/ImpTargetTreeNode.kt
  src/main/java/tree/TargetTreeNode.kt
  src/test/java/e2e/E2EKtTest.kt
  src/test/java/e2e/dot/1.out
  src/test/java/e2e/dot/2.out
  src/test/java/e2e/dot/3.out
  test.tef
  test.tp
Labels: enhancement

#64 Created README file
  README.md
Labels: documentation

#67 Release 1.0.0
  .github/workflows/maven.yml
  .idea/compiler.xml
Labels: enhancement

#76 Created Depth Closure operator
  src/it/kotlin/GivenTreepatExpressionAndTreeThenFindMatchesKtTest.kt
  src/it/kotlin/GivenTreepatExpressionBuildASTNodeTreeKtTest.kt
  src/it/resources/ast/depth_closure/1.in
  src/it/resources/ast/depth_closure/1.msg
  src/it/resources/ast/depth_closure/2.in
  src/it/resources/ast/depth_closure/2.msg
  src/it/resources/expressions_trees_matches/depth_closure/1.msg
  src/it/resources/expressions_trees_matches/depth_closure/1.out
  src/it/resources/expressions_trees_matches/depth_closure/1.tef
  src/it/resources/expressions_trees_matches/depth_closure/1.tp
  src/it/resources/expressions_trees_matches/depth_closure/2.msg
  src/it/resources/expressions_trees_matches/depth_closure/2.out
  src/it/resources/expressions_trees_matches/depth_closure/2.tef
  src/it/resources/expressions_trees_matches/depth_closure/2.tp
  src/it/resources/expressions_trees_matches/depth_closure/3.msg
  src/it/resources/expressions_trees_matches/depth_closure/3.out
  src/it/resources/expressions_trees_matches/depth_closure/3.tef
  src/it/resources/expressions_trees_matches/depth_closure/3.tp
  src/it/resources/expressions_trees_matches/depth_closure/4.msg
  src/it/resources/expressions_trees_matches/depth_closure/4.out
  src/it/resources/expressions_trees_matches/depth_closure/4.tef
  src/it/resources/expressions_trees_matches/depth_closure/4.tp
  src/it/resources/expressions_trees_matches/depth_closure/5.msg
  src/it/resources/expressions_trees_matches/depth_closure/5.out
  src/it/resources/expressions_trees_matches/depth_closure/5.tef
  src/it/resources/expressions_trees_matches/depth_closure/5.tp
  src/it/resources/expressions_trees_matches/depth_closure/6.msg
  src/it/resources/expressions_trees_matches/depth_closure/6.out
  src/it/resources/expressions_trees_matches/depth_closure/6.tef
  src/it/resources/expressions_trees_matches/depth_closure/6.tp
  src/it/resources/expressions_trees_matches/depth_closure/7.msg
  src/it/resources/expressions_trees_matches/depth_closure/7.out
  src/it/resources/expressions_trees_matches/depth_closure/7.tef
  src/it/resources/expressions_trees_matches/depth_closure/7.tp
  src/main/kotlin/antlr/treepat/TreepatVisitorImplementation.kt
  src/main/kotlin/ast/ASTNodes.kt
  src/main/kotlin/operators/ChildFunction.kt
  src/main/kotlin/operators/DepthClosureFunction.kt
  src/main/kotlin/operators/DepthTermFunction.kt
  src/main/kotlin/operators/VisitorFunction.kt
  src/main/kotlin/operators/VisitorFunctionResponse.kt
  src/main/kotlin/target_tree/ImpTargetTreeNode.kt
Labels: enhancement

#73 Created tests for Visitors
  pom.xml
  src/main/kotlin/antlr/tree_format/TreeFormatVisitorImplementation.kt
  src/test/kotlin/antlr/tree_format/TreeFormatVisitorImplementationKtTest.kt
  src/test/kotlin/antlr/treepat/TreepatVisitorImplementationKtTest.kt
Labels: enhancement

#78 Created tests for ast package
  src/test/kotlin/ast/ASTNodeFactoryKtTest.kt
Labels: enhancement
